#!/usr/bin/env bash

set -euo pipefail

if ! command -v tree &>/dev/null; then
    echo "Error: tree is not installed."
    exit 1
fi

PATH_ARG="${1:-.}"

IGNORE_LIST=(
    "target"
    "Cargo.lock"
    ".git"
    "node_modules"
    ".*"
)

IGNORE_PATTERN=$(IFS="|"; echo "${IGNORE_LIST[*]}")

tree -a -I "$IGNORE_PATTERN" "$PATH_ARG"
