preload = ~/Pictures/wallpapers/and-machines.jpg
preload = ~/Pictures/wallpapers/boliviainteligente.jpg
preload = ~/Pictures/wallpapers/jakub-zerdzicki.jpg
preload = ~/Pictures/wallpapers/marcel-strauss.jpg
preload = ~/Pictures/wallpapers/martin-martz.jpg
preload = ~/Pictures/wallpapers/shubham-dhage.jpg

wallpaper = eDP-1,~/Pictures/wallpapers/shubham-dhage.jpg
